name: Isolated Docker Compose Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Get IP Address
      id: get-ip
      run: echo "OPENIM_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV

    - name: Get OpenIM Data DIR
      id: get-dir
      run: echo "DATA_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Run Docker Compose
      run: |
        ./scripts/init-config.sh --force
        docker-compose up -d
        docker-compose ps

    - name: Test OpenIM Server
      run: |
        sleep 30
        docker-compose logs openim-server

    - name: Test OpenIM chat
      run: |
        sleep 30
        docker-compose logs openim-chat

    - name: Check the OpenIM environment and status
      id: docker_info
      run: |
        sleep 30
        echo "images<<EOF" >> $GITHUB_ENV
        sudo docker images >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "containers<<EOF" >> $GITHUB_ENV
        sudo docker ps >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          > [!TIP]
          > Run make install to check the status

          ### Docker Images:
          ```
          ${{ env.images }}
          ```
          ### Docker Processes:
          ```
          ${{ env.containers }}
          ```
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

    - name: stop docker-compose
      run: |
        docker-compose down

    - name: clean all docker containers
      run: |
        docker stop $(docker ps -qa)
        docker rm $(docker ps -qa)
        docker network prune -f

  test-example:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compose-file: 
          - 'example/basic-openim-server-dependency.yml'
          - 'example/full-openim-server-and-chat.yml'
          - 'example/full-openim-server-chat-web.yml'
          - 'example/full-openim-server-chat-web-admin.yml'
          - 'example/only-openim-server.yml'
          - 'example/volume-all-server.yml'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Get IP Address
      id: get-ip
      run: echo "OPENIM_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV

    - name: Get OpenIM Data DIR
      id: get-dir
      run: |
        echo "DATA_DIR=$(pwd)" >> $GITHUB_ENV
        echo $DATA_DIR

    - name: Run Docker ${{ matrix.compose-file }} Compose
      run: |
        ./scripts/init-config.sh --force
        docker-compose -f ${{ matrix.compose-file }} up -d
        docker-compose -f ${{ matrix.compose-file }} ps
        docker-compose -f ${{ matrix.compose-file }} down
        docker stop $(docker ps -qa)
        docker rm $(docker ps -qa)
        docker network prune -f
